# Hotel Reservation Cancellation Project Configuration

# Feature definitions
num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
  - total_nights
  - total_guests
  - price_per_person
  - price_per_night
  - with_children
  - has_weekend_stay

cat_features:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type
  - booking_season

# Target variable
target: is_canceled

# Model parameters for LightGBM classifier
parameters:
  objective: binary
  metric: binary_logloss
  boosting_type: gbdt
  num_leaves: 31
  learning_rate: 0.05
  feature_fraction: 0.9
  bagging_fraction: 0.8
  bagging_freq: 5
  verbose: 0
  random_state: 42
  n_estimators: 100

# MLflow experiment names
experiment_name_basic: "/Users/dylanaustin37@gmail.com/hotel-cancellations-basic"
experiment_name_custom: "/Users/dylanaustin37@gmail.com/hotel-cancellations-custom"

# Environment-specific settings
prd:
  catalog_name: mlops_prd
  schema_name: dylanaus
acc:
  catalog_name: mlops_acc
  schema_name: dylanaus
dev:
  catalog_name: mlops_dev
  schema_name: dylanaus
